#! /bin/bash

sxhkd &
/home/ma/.config/polybar/launch.sh &
setxkbmap -model pc105 -layout us,ru,ua -option grp:alt_shift_toggle &
compton --config ~/.config/compton.conf -b &
feh -z --bg-fill ~/pics/wallpapers/ &

bspc monitor -d web code media edit graphics other

bspc config border_width         2
bspc config window_gap          20

# Set the border colors.
bspc config normal_border_color "#4d4d4d"
bspc config active_border_color "#ff9999"
bspc config focused_border_color "#d9d9d9"
# Use the line below if you are on bspwm >= 0.9.4
bspc config presel_feedback_color "#b2b2b2"

bspc config bottom_padding 0
bspc config top_padding 55

bspc config split_ratio          0.50
#bspc config borderless_monocle   true
bspc config gapless_monocle      false
bspc config click_to_focus       true

bspc rule -a Chromium desktop="web"
bspc rule -a TelegramDesktop desktop="web"
bspc rule -a Subl3 desktop="code"
bspc rule -a URxvt desktop='code' state=floating
bspc rule -a mpv desktop="media"
bspc rule -a Gimp desktop="graphics" follow=on

bspc rule -a feh state=floating

#bspc rule -a mplayer2 state=floating
#bspc rule -a Kupfer.py focus=on
#bspc rule -a Screenkey manage=off